steps:
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'yarn'
  args: ['install']
- name: 'node:10'
  entrypoint: 'yarn'
  id: 'build'
  args: ['build']
  waitFor: ['yarn']
# Run javascript tests.
- name: 'node:10'
  dir: 'tfjs-wechat'
  entrypoint: 'yarn'
  id: 'test-js'
  args: ['test-ci']
  waitFor: ['yarn-common']
  env: ['NIGHTLY=$_NIGHTLY']
timeout: 1800s
logsBucket: 'gs://tfjs-build-logs'
substitutions:
  _NIGHTLY: ''
options:
  logStreamingOption: 'STREAM_ON'
  machineType: 'N1_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
